-- ============================================================
-- Beholder — schema PostgreSQL v2.0.0
--
-- Sucessor do schema SQLite. Mudanças relevantes vs SQLite:
--
--   * UUID nativo (em vez de TEXT) — comparações e indexação mais eficientes.
--   * JSONB (em vez de TEXT) — em todas as colunas que armazenam payloads
--     estruturados. Permite indexação GIN e queries `?`/`@>` nativas.
--   * BOOLEAN (em vez de INTEGER 0/1) — semântica clara, sem cast no app.
--   * TIMESTAMPTZ (em vez de TIMESTAMP/TEXT) — armazena timezone, evita
--     ambiguidades em logs/auditoria distribuídos.
--   * GENERATED BY DEFAULT AS IDENTITY (em vez de AUTOINCREMENT).
--   * IF NOT EXISTS em todos os CREATE TABLE/INDEX e em ALTER TABLE ADD
--     COLUMN — eliminando o ciclo PRAGMA table_info dos antigos migrations.
--
-- Convenção: índices por (created_at DESC) usam ordem reversa para alinhar
-- com a varredura típica "mais recente primeiro" das telas (auditoria,
-- presentations, finops).
-- ============================================================

-- Auth & RBAC
CREATE TABLE IF NOT EXISTS users (
    id              UUID PRIMARY KEY,
    username        TEXT NOT NULL UNIQUE,
    full_name       TEXT NOT NULL DEFAULT '',
    email           TEXT NOT NULL DEFAULT '',
    phone           TEXT NOT NULL DEFAULT '',
    department      TEXT NOT NULL DEFAULT '',
    title           TEXT NOT NULL DEFAULT '',
    hashed_password TEXT NOT NULL,
    salt            TEXT NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS roles (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS permissions (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id UUID    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       INTEGER NOT NULL REFERENCES roles(id)       ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

-- Module Registry
CREATE TABLE IF NOT EXISTS modules (
    id              UUID PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    endpoint_url    TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'active',
    config_params   JSONB,
    description     TEXT NOT NULL DEFAULT '',
    skill_path      TEXT,
    response_type   TEXT NOT NULL DEFAULT 'text',
    response_config JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- API Endpoints externos (configurados pelo admin para uso por módulos
-- response_type='api')
CREATE TABLE IF NOT EXISTS api_endpoints (
    id              UUID PRIMARY KEY,
    name            TEXT NOT NULL UNIQUE,
    description     TEXT NOT NULL DEFAULT '',
    url             TEXT NOT NULL,
    method          TEXT NOT NULL DEFAULT 'POST',
    headers         JSONB,
    timeout_seconds INTEGER NOT NULL DEFAULT 30,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Histórico de chamadas a APIs externas (auditoria + debug)
CREATE TABLE IF NOT EXISTS api_calls (
    id              UUID PRIMARY KEY,
    api_endpoint_id UUID NOT NULL REFERENCES api_endpoints(id),
    module_id       UUID,
    user_id         UUID,
    request_body    JSONB,
    response_status INTEGER,
    response_body   JSONB,
    duration_ms     DOUBLE PRECISION,
    error           TEXT,
    called_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_api_calls_endpoint
    ON api_calls(api_endpoint_id, called_at DESC);

-- Prompts (guardrail-system-guardrail)
CREATE TABLE IF NOT EXISTS prompts (
    id               UUID PRIMARY KEY,
    module_name      TEXT,                   -- legado (mantido para compat)
    module_names     JSONB,                  -- nova: lista de módulos
    name             TEXT NOT NULL,
    version          INTEGER NOT NULL,
    input_guardrail  TEXT,
    system_prompt    TEXT NOT NULL,
    output_guardrail TEXT,
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (name, version)
);
CREATE INDEX IF NOT EXISTS idx_prompts_name        ON prompts(name);
CREATE INDEX IF NOT EXISTS idx_prompts_module_name ON prompts(module_name);
-- GIN sobre JSONB permite procurar prompts cujo array contenha o módulo X.
CREATE INDEX IF NOT EXISTS idx_prompts_module_names ON prompts USING GIN (module_names);

-- ===== Rastreabilidade (Audit Trail) =====
-- Registra TODAS as ações: chamadas HTTP, execuções de módulo, mudanças de
-- configuração, uploads, etc.
CREATE TABLE IF NOT EXISTS audit_events (
    id          UUID PRIMARY KEY,
    ts          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id     UUID,
    username    TEXT,
    category    TEXT NOT NULL,
    action      TEXT NOT NULL,
    target      TEXT,
    status_code INTEGER,
    duration_ms DOUBLE PRECISION,
    feature     TEXT,
    payload     JSONB,
    error       TEXT,
    ip          TEXT,
    user_agent  TEXT
);
CREATE INDEX IF NOT EXISTS idx_audit_ts       ON audit_events(ts DESC);
CREATE INDEX IF NOT EXISTS idx_audit_category ON audit_events(category, ts DESC);
CREATE INDEX IF NOT EXISTS idx_audit_user     ON audit_events(user_id, ts DESC);
CREATE INDEX IF NOT EXISTS idx_audit_feature  ON audit_events(feature, ts DESC);
-- Alta seletividade em busca por status >= 400 (filtro recorrente da página).
CREATE INDEX IF NOT EXISTS idx_audit_status_err
    ON audit_events(status_code, ts DESC) WHERE status_code >= 400;

-- FinOps Ledger — dimensões de chargeback/showback modernas:
--   domain, product, agent, flow, prompt_id, integration, environment.
-- Latência (latency_ms) e storage (storage_bytes) são opcionais. Todas as
-- colunas começam nullable para gravações antigas continuarem válidas.
CREATE TABLE IF NOT EXISTS finops_ledger (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         UUID,
    module_id       UUID,
    model_name      TEXT,
    tokens_input    INTEGER NOT NULL DEFAULT 0,
    tokens_output   INTEGER NOT NULL DEFAULT 0,
    cost_estimated  DOUBLE PRECISION NOT NULL DEFAULT 0,
    context_tag     TEXT NOT NULL DEFAULT '',
    domain          TEXT,
    product         TEXT,
    agent           TEXT,
    flow            TEXT,
    prompt_id       TEXT,
    integration     TEXT,
    environment     TEXT NOT NULL DEFAULT 'production',
    latency_ms      DOUBLE PRECISION,
    storage_bytes   BIGINT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_finops_created     ON finops_ledger(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_finops_model       ON finops_ledger(model_name);
CREATE INDEX IF NOT EXISTS idx_finops_domain      ON finops_ledger(domain);
CREATE INDEX IF NOT EXISTS idx_finops_agent       ON finops_ledger(agent);
CREATE INDEX IF NOT EXISTS idx_finops_environment ON finops_ledger(environment);
-- Índice composto para a query do Cockpit (filtros típicos: 24h por modelo).
CREATE INDEX IF NOT EXISTS idx_finops_ts_model
    ON finops_ledger(created_at DESC, model_name);
-- Para chargeback por módulo (extrai prefixo de context_tag antes da '/')
-- via SPLIT_PART. Index parcial para acelerar GROUP BY agregações comuns.
CREATE INDEX IF NOT EXISTS idx_finops_context_tag ON finops_ledger(context_tag);

-- FinOps Budgets
CREATE TABLE IF NOT EXISTS finops_budgets (
    id                UUID PRIMARY KEY,
    name              TEXT NOT NULL,
    scope_type        TEXT NOT NULL,
    scope_value       TEXT,
    period            TEXT NOT NULL DEFAULT 'monthly',
    limit_brl         DOUBLE PRECISION NOT NULL,
    warning_threshold DOUBLE PRECISION NOT NULL DEFAULT 0.8,
    hard_stop         BOOLEAN NOT NULL DEFAULT FALSE,
    notes             TEXT,
    created_by        UUID,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_budgets_scope
    ON finops_budgets(scope_type, scope_value);

-- FinOps Model Policies
CREATE TABLE IF NOT EXISTS finops_model_policies (
    id                  UUID PRIMARY KEY,
    model_name          TEXT NOT NULL UNIQUE,
    risk_tier           TEXT NOT NULL DEFAULT 'medium',
    value_tier          TEXT NOT NULL DEFAULT 'medium',
    max_cost_per_call   DOUBLE PRECISION,
    max_tokens_per_call INTEGER,
    allowed_features    JSONB,
    rationale           TEXT,
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- FinOps Alerts
CREATE TABLE IF NOT EXISTS finops_alerts (
    id              UUID PRIMARY KEY,
    budget_id       UUID NOT NULL REFERENCES finops_budgets(id) ON DELETE CASCADE,
    severity        TEXT NOT NULL,
    cost_observed   DOUBLE PRECISION NOT NULL,
    limit_reference DOUBLE PRECISION NOT NULL,
    period_start    TIMESTAMPTZ,
    period_end      TIMESTAMPTZ,
    triggered_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at     TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_alerts_budget
    ON finops_alerts(budget_id, triggered_at DESC);

-- Artefatos efêmeros gerados por execuções de módulo (CSV, MD, JSON…).
-- TTL gerenciado no SELECT (filtra por created_at). GC opcional via DELETE
-- WHERE created_at < NOW() - INTERVAL '30 min' (chamado manualmente).
-- Substitui o dict in-memory anterior; agora persiste cross-worker e
-- sobrevive a restart.
CREATE TABLE IF NOT EXISTS artifacts (
    id          UUID PRIMARY KEY,
    filename    TEXT NOT NULL,
    mime_type   TEXT NOT NULL,
    content     BYTEA NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_artifacts_created_at
    ON artifacts(created_at DESC);

-- ===== Funcionalidades por Perfil — matriz (role × dept × feature) =====
-- Tela administrativa onde root configura quais funcionalidades cada perfil
-- pode acessar. Resolve gaps que page-level role gates não cobrem: por
-- exemplo, "analista_n3 do dept vendas vê /radar, do dept compras não vê".
--
-- Política de match (helper FeatureAccessService.can_access):
--   1. Sem nenhuma regra para (role, dept, feature) → ALLOW (default).
--      Migrate-safe: instalações existentes mantêm comportamento atual.
--   2. Regra com dept específico vence regra com dept='' (wildcard).
--   3. access=FALSE em qualquer regra match → DENY.
--   4. access=TRUE em regra match → ALLOW explícito.
--   5. ``root`` no set de roles do user → ALLOW (bypass total, supremo).
--
-- ``role`` armazena UM role por linha. Para um user com múltiplos roles,
-- o helper checa cada role separadamente — ALLOW se PELO MENOS UM permite.
-- ``department`` armazena dept exato OU '' (wildcard que casa qualquer).
-- ``feature_key`` é um slug curto ('radar', 'raiox' atualmente; futuro:
-- 'prompts', 'gallery', etc.).
CREATE TABLE IF NOT EXISTS feature_access (
    id                       UUID PRIMARY KEY,
    role                     TEXT NOT NULL,
    department               TEXT NOT NULL DEFAULT '',
    feature_key              TEXT NOT NULL,
    access                   BOOLEAN NOT NULL,
    created_by_id            TEXT,
    created_by_username      TEXT,
    updated_by_id            TEXT,
    updated_by_username      TEXT,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (role, department, feature_key)
);
CREATE INDEX IF NOT EXISTS idx_feature_access_lookup
    ON feature_access(role, feature_key);

